import { Cross2Icon } from "@radix-ui/react-icons"
import {
  Check,
  CreditCard,
  Crop,
  Gauge,
  LayoutDashboard,
  Minimize2,
  Monitor,
  Palette,
  Rocket,
  RotateCcw,
  ScrollText,
  Settings,
  ShoppingBasket,
  Store,
  Trash,
  Upload,
  User,
  Users,
  Zap,
} from "lucide-react"

export const Icons = {
  store: Store,
  credit: CreditCard,
  user: User,
  rocket: Rocket,
  gauge: Gauge,
  layoutDashboard: LayoutDashboard,
  monitor: Monitor,
  shoppingBasket: ShoppingBasket,
  minimize2: Minimize2,
  palette: Palette,
  scrollText: ScrollText,
  users: Users,
  zap: Zap,
  settings: Settings,
  check: Check,
  upload: Upload,
  trash: Trash,
  crop: Crop,
  reset: RotateCcw,
  cross2: Cross2Icon,
}
