import {
  Check,
  CreditCard,
  Gauge,
  LayoutDashboard,
  Minimize2,
  Monitor,
  Palette,
  Rocket,
  ScrollText,
  Settings,
  ShoppingBasket,
  Store,
  User,
  Users,
  Zap,
} from "lucide-react"

export const Icons = {
  store: Store,
  credit: CreditCard,
  user: User,
  rocket: Rocket,
  gauge: Gauge,
  layoutDashboard: LayoutDashboard,
  monitor: Monitor,
  shoppingBasket: ShoppingBasket,
  minimize2: Minimize2,
  palette: Palette,
  scrollText: ScrollText,
  users: Users,
  zap: Zap,
  settings: Settings,
  check: Check,
}
